export const BillTypes = {
  EXPENSE: 'EXPENSE',
  INCOME: 'INCOME',
  REPEATED_INCOME: 'REPEATED_INCOME',
  REPEATED_EXPENSE: 'REPEATED_EXPENSE',
};

export const BillStatus = {
  PAID: 'PAID',
  NOT_PAID: 'NOT_PAID',
  PENDING: 'PENDING',
};
